accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("update/<int:pk>/", views.update, name="update"),
    path("<int:pk>/password/", views.change_pw, name="password"),
    path("<int:pk>/withdrawal/", views.withdrawal, name="withdrawal"),
]

articles/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = "articles"


urlpatterns = [
    path("reviews/", views.reviews, name="reviews"),
    path("search/", views.search, name="search"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
    path("<int:pk>/add-like", views.add_like, name="add-like"),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/update/",
        views.comment_update,
        name="comment_update",
    ),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

# 정적 파일 설정
# https://docs.djangoproject.com/en/4.1/howto/static-files/

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("index.urls")),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [
    path("", views.index, name="index"),
    path("intro/", views.intro, name="intro"),
    path("contrib/", views.contrib, name="contrib"),
]

accounts/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator, MaxLengthValidator


def input_only_number(value):
    if not value.isdigit():
        raise ValidationError("숫자만 적을 수 있습니다.")


# Create your models here.
class User(AbstractUser):
    @property
    def full_name(self):
        return f'{self.last_name}{self.first_name}'


class UserPhoneNumber(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(
        max_length=11,
        validators=[MinLengthValidator(11), MaxLengthValidator(11), input_only_number],
        blank=True,
    )

articles/models.py
from django.db import models
from django.contrib.auth import get_user_model
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Article(models.Model):
    content = models.TextField()
    title = models.CharField(max_length=50)
    movie_name = models.CharField(max_length=30)
    grade = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    view = models.PositiveIntegerField(default=0)
    thumbnail = ProcessedImageField(
        upload_to="thumbnail/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={
            "quality": 60,
        },
    )
    image = models.ImageField(
        upload_to="images/",
        blank=True,
    )


class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)


class Like(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from .models import UserPhoneNumber
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    PasswordChangeForm,
)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "last_name",
            "first_name",
            "email",
        )
        widgets = {
            "username": forms.TextInput(
                attrs={
                    "placeholder": "",
                }
            ),
            "last_name": forms.TextInput(
                attrs={
                    "placeholder": "",
                }
            ),
            "first_name": forms.TextInput(
                attrs={
                    "placeholder": "",
                }
            ),
            "email": forms.TextInput(
                attrs={
                    "placeholder": "",
                }
            ),
        }


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "last_name",
            "first_name",
            "email",
        )
        widgets = {
            "username": forms.TextInput(
                attrs={
                    "placeholder": "",
                }
            ),
            "last_name": forms.TextInput(
                attrs={
                    "placeholder": "",
                }
            ),
            "first_name": forms.TextInput(
                attrs={
                    "placeholder": "",
                }
            ),
            "email": forms.TextInput(
                attrs={
                    "placeholder": "",
                }
            ),
        }


class CustomPasswordChangeForm(PasswordChangeForm):
    def clean_new_password1(self):
        old = self.cleaned_data.get("old_password")
        new = self.cleaned_data.get("new_password1")
        if old == new:
            raise forms.ValidationError("이전 비밀번호와 새 비밀번호가 같습니다.")


class UserPhoneNumberForm(forms.ModelForm):
    class Meta:
        model = UserPhoneNumber
        fields = ("phone",)
        labels = {
            "phone": "휴대폰",
        }
        widgets = {
            "phone": forms.TextInput(
                attrs={
                    "placeholder": "'-' 를 제외하고 입력해주세요.",
                    "style": "width: 100%; resize: none;",
                }
            ),
        }

accounts/views.py
import random
from django.contrib import messages
from .forms import UserPhoneNumberForm
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth import login as login_
from django.contrib.auth import logout as logout_
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import (
    CustomUserCreationForm,
    CustomUserChangeForm,
    CustomPasswordChangeForm,
)

greetings = [
    "안녕하세요.",
    "환영합니다!",
    "반갑습니다.",
    "반가워요!",
]
check_user_name = [
    "이름을 등록해주세요!",
    "아직 이름을 입력하지 않으셨네요!",
]
bye = [
    "안녕히가세요.",
    "잘가요!",
    "다음에 또 오세요!",
    "다음에 또 봐요!",
]
wd = [
    "당신이 그리울 거에요...",
    "다음에 또 오세요!",
]

# 회원가입


def signup(request):
    if request.user.username:
        messages.warning(request, "이미 가입 하셨군요!")
        return render(request, "400.html", status=400)
    else:
        if request.method == "POST":
            form = CustomUserCreationForm(request.POST)
            pn_form = UserPhoneNumberForm(request.POST)
            if form.is_valid() and pn_form.is_valid():
                user = form.save()
                user_phone_number = pn_form.save(commit=False)
                user_phone_number.user = user
                phone = user_phone_number.phone
                if phone:
                    p1 = "".join(phone[:3])
                    p2 = "".join(phone[3:7])
                    p3 = "".join(phone[7:])
                    phone = "-".join([p1, p2, p3])
                else:
                    pass
                user_phone_number.phone = phone
                user_phone_number.save()
                login_(request, user)
                g = random.choice(greetings)
                c = random.choice(check_user_name)
                if user.full_name:
                    messages.success(request, f"{user.full_name}님, {g}")
                else:
                    messages.success(request, f"익명의 사용자님, {g}")
                    messages.warning(request, f"{c}")
                return redirect("articles:reviews")
        else:
            form = CustomUserCreationForm()
            pn_form = UserPhoneNumberForm()
        context = {
            "form": form,
            "pn_form": pn_form,
        }
        return render(request, "accounts/form.html", context)


# 로그인
def login(request):
    if request.user.username:
        messages.warning(request, "이미 로그인 하셨군요!")
        return render(request, "400.html", status=400)
    else:
        if request.method == "POST":
            form = AuthenticationForm(request.POST, data=request.POST)
            if form.is_valid():
                login_(request, form.get_user())
                g = random.choice(greetings)
                c = random.choice(check_user_name)
                if form.get_user().full_name:
                    messages.error(request, f"{form.get_user().full_name}님, {g}")
                else:
                    messages.error(request, f"익명의 사용자님, {g}")
                    messages.warning(request, f"{c}")
                return redirect(request.GET.get("next") or "articles:reviews")
        else:
            form = AuthenticationForm()
        context = {
            "form": form,
        }
        return render(request, "accounts/login.html", context)


# 로그아웃
@login_required
def logout(request):
    b = random.choice(bye)
    if request.user.full_name:
        messages.error(request, f"{request.user.full_name}님, {b}")
    else:
        messages.error(request, f"익명의 사용자님, {b}")
    logout_(request)
    return redirect(request.META.get("HTTP_REFERER", "redirect_if_referer_not_found"))


# 회원정보조회
def detail(request, pk):
    now_user = request.user
    other_user = get_user_model().objects.get(id=pk)
    context = {
        "now_user": now_user,
        "other_user": other_user,
    }
    return render(request, "accounts/detail.html", context)


# 회원정보수정
@login_required
def update(request, pk):
    now_user = request.user
    other_user = get_user_model().objects.get(id=pk)
    if other_user.username != "admin":
        phone = other_user.userphonenumber
    else:
        messages.error(request, "관리자 계정은 일반 페이지에서 수정이 불가능합니다.")
        messages.warning(request, "관리자 페이지를 이용해주세요.")
        return redirect("accounts:detail", other_user.pk)
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=other_user)
        pn_form = UserPhoneNumberForm(request.POST, instance=phone)
        if form.is_valid() and pn_form.is_valid():
            user = form.save()
            user_phone_number = pn_form.save(commit=False)
            user_phone_number.user = user
            phone = user_phone_number.phone
            if phone:
                p1 = "".join(phone[:3])
                p2 = "".join(phone[3:7])
                p3 = "".join(phone[7:])
                phone = "-".join([p1, p2, p3])
                user_phone_number.phone = phone
            else:
                pass
            user_phone_number.save()
            messages.success(request, "정보가 변경되었습니다.")
            return redirect("accounts:detail", other_user.pk)
    else:
        form = CustomUserChangeForm(instance=other_user)
        pn_form = UserPhoneNumberForm(instance=phone)
    context = {
        "form": form,
        "pn_form": pn_form,
        "now_user": now_user,
        "other_user": other_user,
    }
    return render(request, "accounts/form.html", context)


# 회원탈퇴
@login_required
def withdrawal(request, pk):
    user = get_user_model().objects.get(id=pk)
    w = random.choice(wd)
    b = random.choice(bye)
    if request.method == "POST":
        if request.user.full_name:
            messages.success(request, f"{request.user.full_name}!, {w}")
        else:
            messages.success(request, f"{b}")
        request.user.delete()
        logout_(request)
        return redirect("articles:reviews")
    else:
        context = {
            "user": user,
        }
    return render(request, "accounts/withdrawal.html", context)


# 비밀번호 변경
@login_required
def change_pw(request, pk):
    user = request.user
    if request.method == "POST":
        form = CustomPasswordChangeForm(user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, "비밀번호가 변경되었습니다.")
            return redirect("accounts:profile", user.pk)
    else:
        form = CustomPasswordChangeForm(user)
    context = {
        "form": form,
        "user": user,
    }
    return render(request, "accounts/password.html", context)


# 에러 처리


def error_400(request, exception):
    return render(request, "400.html", status=400)


def error_403(request, exception):
    return render(request, "403.html", status=403)


def error_404(request, exception):
    return render(request, "404.html", status=404)


def error_500(request):
    return render(request, "500.html", status=500)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
  <div class="mt-5">
    <h1 class="mb-3">{{ other_user.username }}님의 프로필</h1>
    <table class="table table-hover table-bordered">
      <tbody class="table-group-divider">
        <tr>
          <th class="col-1">이름</th>
          <td class="col-11">{{ other_user.full_name }}</td>
        </tr>
        <tr>
          <th class="col-1">이메일</th>
          <td>{{ other_user.email }}</td>
        </tr>
        <tr>
          <th class="col-1">연락처</th>
          <td>{{ other_user.userphonenumber.phone }}</td>
        </tr>
        <tr>
          <th class="col-1">가입일</th>
          <td>{{ other_user.date_joined|date:"y년 m월 d일 f:s" }}</td>
        </tr>
      </tbody>
    </table>
    {% if other_user == now_user or now_user.is_superuser %}
    <div class="d-flex mt-3 mb-5">
      <a href="{% url 'accounts:update' other_user.pk %}" class="btn btn-primary ms-0">프로필 수정</a>
      <a href="{% url 'accounts:password' other_user.pk %}" class="btn btn-primary mx-3">비밀번호 변경</a>
      <a href="{% url 'articles:reviews' %}" class="btn btn-primary mx-0">리뷰 목록</a>
      <a href="{% url 'accounts:withdrawal' other_user.pk %}" class="btn btn-danger ms-auto">계정 탈퇴</a>
    </div>
    <h1 class="text-center my-5">작성 리뷰 정보</h1>
    <div class="row mb-4">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th class="col-6 p-0">
              <h3>작성한 글</h3>
              {% if user.review_set.count > 0 %}
              <table class="table m-0 p-0">
                <thead class="table-hover table-bordered">
                  <tr>
                    <th class="col-2">번호</th>
                    <th class="col-4 border-end">제목</th>
                  </tr>
                </thead>

                <tbody class="table-group-divider">
                  <tr>
                    <th class="text-muted">작성한 글 개수</th>
                    <td class="text-muted border-end">{{ user.review_set.count }} 개의 글을 작성하였습니다.</td>
                  </tr>
                  {% for article in user.review_set.all %}
                  <tr>
                    <th>{{ forloop.counter }}</th>
                    <td class="border-end"><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% else %}
              <p class="lead">작성한 글이 없습니다.</p>
              {% endif %}
            </th>
            <th class="col-6 p-0">
              <h3>작성한 댓글</h3>
              {% if user.comment_set.count > 0 %}
              <table class="table m-0 p-0">
                <thead class="table-hover table-bordered">
                  <tr>
                    <th class="col-2">번호</th>
                    <th class="col-4">내용</th>
                  </tr>
                </thead>
                <tbody class="table-group-divider">
                  <tr>
                    <th class="text-muted">작성한 댓글 개수</th>
                    <td class="text-muted">{{ user.comment_set.count }} 개의 댓글을 작성하였습니다.</td>
                  </tr>
                  {% for comment in user.comment_set.all %}
                  <tr>
                    <th>{{ forloop.counter }}</th>
                    <td><a href="{% url 'articles:detail' comment.article_id %}">{{ comment.content }}</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% else %}
              <p class="lead">작성한 댓글이 없습니다.</p>
              {% endif %}
            </th>
          </tr>
        </tbody>
      </table>
    </div>
    {% else %}
    <h1 class="text-center my-5">작성 글 조회 권한이 없습니다.</h1>
    {% endif %}
  </div>
</div>

{% endblock body %}

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}

<div class="container w-25 mt-5 mb-5 pb-5">
  {% if request.resolver_match.url_name == "signup" %}
  <h1>회원 가입</h1>
  <form action="" method="POST" class="form">
    {% csrf_token %}
    <div class="card pt-4 pb-2 px-3 my-3">
      <h3 class="text-center mt-2 mb-5">필수 입력</h3>
      {% for field in form %}
      {% if field.name == "username" or field.name == "password1" or field.name == "password2" %}
      <div>{% bootstrap_field field %}</div>
      {% endif %}
      {% endfor %}
    </div>
    <div class="card pt-4 pb-2 px-3 my-3">
      <h3 class="text-center mt-2 mb-5">선택사항</h3>
      {% for field in form %}
      {% if field.name != "username" and field.name != "password1" and field.name != "password2" %}
      <div>{% bootstrap_field field %}</div>
      {% endif %}
      {% endfor %}
      {% bootstrap_form pn_form %}
    </div>
    <div class="d-flex mb-5">
      {% bootstrap_button button_type="submit" content="완료" style="width: 6rem;" %}
      <a href="{% url 'articles:reviews' %}" class="btn btn-primary ms-auto" style="width: 6rem;">돌아가기</a>
    </div>
  </form>
  {% else %}
  {% if other_user == now_user or now_user.is_superuser %}
  <h1>회원정보 수정</h1>
  <form action="" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_form pn_form %}
    <div class="d-flex mb-5">
      {% bootstrap_button button_type="submit" content="완료" style="width: 6rem;" %}
      <a href="{% url 'accounts:detail' user.pk %}" class="btn btn-primary ms-auto" style="width: 6rem;">돌아가기</a>
    </div>
  </form>
  {% else %}
  <h1>권한이 없습니다.</h1>
  {% endif %}
  {% endif %}
</div>
{% endblock body %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

<div class="container w-25 mt-5">
  <h1 class="mt-5 text-center">로그인</h1>
  <div>
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="d-flex">
        {% bootstrap_button button_type="submit" content="로그인" %}
        <a class="btn btn-primary ms-auto" href="{% url 'accounts:signup' %}">회원가입</a>
      </div>
    </form>
  </div>

</div>

{% endblock body %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

<div class="container w-25 mt-5">
  {% if user == request.user or user.is_superuser %}
  <form action="" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="비밀번호 변경" %}
    <a href="{% url 'accounts:detail' user.pk %}" class="btn btn-primary ms-2">돌아가기</a>
  </form>
  {% else %}
  <h1>권한이 없습니다.</h1>
  {% endif %}
</div>

{% endblock body %}

accounts/templates/accounts/withdrawal.html
{% extends 'base.html' %}

{% block body %}

<div class="container w-25 mt-5">
  <div class="card">
    <div class="card-body">
      <form action="" method="POST">
        {% csrf_token %}
        <h2 class="card-title mb-5 text-center">정말로 탈퇴 하시겠습니까?</h2>
        <div class="mt-5 text-center">
          <input class="btn btn-danger" type="submit" value="예" style="width: 5rem;">
          <a href="{% url 'accounts:detail' user.pk %}" class="btn btn-primary ms-2" style="width: 5rem;">아니오</a>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock body %}