accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("update/<int:pk>/", views.update, name="update"),
    path("<int:pk>/password/", views.change_pw, name="password"),
    path("<int:pk>/withdrawal/", views.withdrawal, name="withdrawal"),
]

articles/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = "articles"


urlpatterns = [
    path("reviews/", views.reviews, name="reviews"),
    path("search/", views.search, name="search"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
    path("<int:pk>/add-like", views.add_like, name="add-like"),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/update/",
        views.comment_update,
        name="comment_update",
    ),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

# 정적 파일 설정
# https://docs.djangoproject.com/en/4.1/howto/static-files/

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("index.urls")),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [
    path("", views.index, name="index"),
    path("intro/", views.intro, name="intro"),
    path("contrib/", views.contrib, name="contrib"),
]

articles/models.py
from django.db import models
from django.contrib.auth import get_user_model
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Article(models.Model):
    content = models.TextField()
    title = models.CharField(max_length=50)
    movie_name = models.CharField(max_length=30)
    grade = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    view = models.PositiveIntegerField(default=0)
    thumbnail = ProcessedImageField(
        upload_to="thumbnail/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={
            "quality": 60,
        },
    )
    image = models.ImageField(
        upload_to="images/",
        blank=True,
    )


class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)


class Like(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = [
            "title",
            "movie_name",
            "content",
            "grade",
            "image",
            "thumbnail",
        ]
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "placeholder": "리뷰 제목은 50자 이내로 작성해주세요.",
                    "style": "height: 2.5rem; resize: none;",
                }
            ),
            "movie_name": forms.TextInput(
                attrs={
                    "placeholder": "영화 제목은 30자 이내로 작성해주세요.",
                    "style": "height: 2.5rem; resize: none;",
                }
            ),
            "content": forms.Textarea(
                attrs={
                    "placeholder": "",
                    "style": "height: 15rem; resize: none;",
                }
            ),
        }
        labels = {
            "title": "리뷰 제목",
            "movie_name": "영화 제목",
            "content": "내용",
            "grade": "평점",
            "image": "본문 사진",
            "thumbnail": "썸네일",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "",
                    "style": "height: 100px; resize: none; width: 100%;",
                }
            ),
        }
        labels = {
            "content": "댓글",
        }


class MiniCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "",
                    "style": "height: 100px; resize: none; width: 100%;",
                }
            ),
        }
        labels = {
            "content": "",
        }

articles/views.py
from .forms import ArticleForm, CommentForm, MiniCommentForm
from django.contrib.auth.decorators import login_required
from datetime import date, datetime, timedelta
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from .models import Article, Comment, Like
from django.contrib import messages
from django.db.models import Q

# Create your views here.
def reviews(request):
    articles = Article.objects.order_by("-id")
    context = {
        "articles": articles,
    }
    return render(request, "articles/reviews.html", context)


@login_required
def create(request):
    user = request.user
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = user
            article.save()
            messages.success(request, "작성하였습니다.")
            return redirect("articles:reviews")
    else:
        form = ArticleForm()
    context = {
        "form": form,
    }
    return render(request, "articles/form.html", context)


def search(request):
    if request.method == "POST":
        search = request.POST["search"]
        searched_users = get_user_model().objects.filter(username__contains=search)
        searched_articles = Article.objects.filter(
            Q(title__icontains=search)
            | Q(content__icontains=search)
            | Q(movie_name__icontains=search)
        )
        context = {
            "search": search,
            "searched_users": searched_users,
            "searched_articles": searched_articles,
        }
        return render(request, "articles/reviews.html", context)


def detail(request, pk):
    if request.user.is_authenticated:
        user_recommends = request.user.like_set.all()
        try:
            flag = user_recommends.get(article_id=pk)
        except:
            flag = 0
        target_article = Article.objects.get(id=pk)
        like_ = Like.objects.filter(article=target_article)
        like_length = len(like_)
        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.article = target_article
                comment.user = request.user
                comment.save()
                messages.success(request, "작성하였습니다.")
                return redirect("articles:detail", target_article.pk)
        else:
            form = CommentForm()
        context = {
            "flag": flag,
            "article": target_article,
            "like_length": like_length,
            "like_": like_,
            "form": form,
        }

        response = render(request, "articles/detail.html", context)

        # 조회수
        # expire_date, now = datetime.now(), datetime.now()
        # expire_date += timedelta(days=1)
        # expire_date = expire_date.replace(hour=0, minute=0, second=0, microsecond=0)
        # expire_date -= now
        # max_age = expire_date.total_seconds()
        # cookie_value = request.COOKIES.get("hitboard", "_")
        # if not f"_{pk}_" in cookie_value:
        #     cookie_value += f"{pk}_"
        #     response.set_cookie(
        #         "hitboard", value=cookie_value, max_age=max_age, httponly=True
        #     )

        target_article.view += 1
        target_article.save()
        return response
    else:
        target_article = Article.objects.get(id=pk)
        like_ = Like.objects.filter(article=target_article)
        like_length = len(like_)
        context = {
            "article": target_article,
            "like_length": like_length,
            "like_": like_,
        }
        target_article.view += 1
        target_article.save()
        return render(request, "articles/detail.html", context)


@login_required
def update(request, pk):
    user = request.user
    like_ = Like.objects.all()
    article = Article.objects.get(id=pk)
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            messages.success(request, "수정되었습니다.")
            return redirect("articles:detail", article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        "form": form,
        "user": user,
        "like_": like_,
        "article": article,
    }
    return render(request, "articles/form.html", context)


@login_required
def delete(request, pk):
    article = Article.objects.get(id=pk)
    user = request.user
    if request.method == "POST":
        article.delete()
        messages.success(request, "삭제되었습니다.")
        return redirect("articles:reviews")
    context = {
        "article": article,
        "user": user,
    }
    return render(request, "articles/delete.html", context)


@login_required
def comment_update(request, article_pk, comment_pk):
    form = CommentForm()
    user_recommends = request.user.like_set.all()
    try:
        flag = user_recommends.get(article_id=article_pk)
    except:
        flag = 0
    user = request.user
    article = Article.objects.get(id=article_pk)
    like_ = Like.objects.filter(article=article)
    like_length = len(like_)
    target_comment = Comment.objects.get(id=comment_pk)
    if user.pk == target_comment.user.pk:
        if request.method == "POST":
            comment_form = MiniCommentForm(request.POST, instance=target_comment)
            if comment_form.is_valid():
                comment_form.save()
                messages.success(request, "수정되었습니다.")
                return redirect("articles:detail", article.pk)
        else:
            comment_form = MiniCommentForm(instance=target_comment)
        context = {
            "flag": flag,
            "like_length": like_length,
            "target_comment": target_comment,
            "article": article,
            "form": form,
            "comment_form": comment_form,
            "user": user,
        }
        return render(request, "articles/detail.html", context)
    else:
        messages.warning(request, "권한이 없습니다.")
        return redirect("articles:detail", article_pk)


@login_required
def comment_delete(request, article_pk, comment_pk):
    user = request.user
    comment = Comment.objects.get(id=comment_pk)
    if user.pk == comment.user.pk:
        comment.delete()
        messages.success(request, "삭제되었습니다.")
        return redirect("articles:detail", article_pk)
    else:
        messages.warning(request, "권한이 없습니다.")
        return redirect("articles:detail", article_pk)


@login_required
def add_like(request, pk):
    target_article = Article.objects.get(id=pk)
    target_user = request.user
    try:
        if target_article.like_set.get(user=target_user):
            like_ = Like.objects.filter(user=target_user, article=target_article)
            like_.delete()
            return redirect("articles:detail", target_article.pk)
        else:
            like_ = Like.objects.create(article=target_article, user=target_user)
            like_.save()
            return redirect("articles:detail", target_article.pk)
    except:
        like_ = Like.objects.create(article=target_article, user=target_user)
        like_.save()
        messages.warning(request, "추천!")
        return redirect("articles:detail", target_article.pk)


# 에러 처리


def error_400(request, exception):
    return render(request, "400.html", status=400)


def error_403(request, exception):
    return render(request, "403.html", status=403)


def error_404(request, exception):
    return render(request, "404.html", status=404)


def error_500(request):
    return render(request, "500.html", status=500)

articles/templates/articles/delete.html
{% extends 'base.html' %}

{% block body %}

<div class="container w-25 mt-5">
  {% if user == article.user or user.is_superuser %}
  <div class="card w-75">
    <div class="card-body">
      <form action="" method="POST" class="text-center">
        {% csrf_token %}
        <p class="mb-1 lead">삭제 : {{ article.title }}</p>
        <p class="card-title lead">삭제 하시겠습니까?</p>
        <div class="mt-5">
          <input class="btn btn-danger" type="submit" value="예" style="width: 5rem;">
          <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary ms-2" style="width: 5rem;">아니오</a>
        </div>
      </form>
    </div>
  </div>
  {% else %}
  <h1>권한이 없습니다.</h1>
  <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">돌아가기</a>
  {% endif %}
</div>

{% endblock body %}

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load custom_tags %}

{% block body %}

<div class="container">
  <div class="card p-5">
    <div class="card-body">
      <h1 class="card-title mb-0">{{ article.title }}</h1>
      <div class="card-subtitle mt-2">
        <!-- 작성자 및 글 정보 -->
        <div class="d-flex">
          <h6 class="text-muted">{{ article.movie_name }}</h6>
          <h6 class="mx-2">
            {% for i in article.grade|star_range %}
            <i class="bi bi-star-fill text-warning"></i>
            {% endfor %}
          </h6>
        </div>
        <div class="text-muted d-flex">
          <h6>
            {{ article.user }} | {{ article.created_at|date:"Y.m.d H:m:s" }}
          </h6>
          <h6 class="ms-auto">
            추천 {{ like_|length }} | 댓글 {{ article.comment_set.all|length }} | 조회수 {{ article.view }}
          </h6>
        </div>
      </div>
      {% if article.image %}
      <img src="{{ article.image.url }}" alt="{{ article.image }}" class="my-5">
      {% endif %}
      <p class="card-text lead my-5">{{ article.content }}</p>
      <!-- 추천 -->
      <div class="text-center" style="margin-top: 10rem; margin-bottom: 5rem;">
        <form action="{% url 'articles:add-like' article.pk %}" method="POST">
          {% csrf_token %}
          <h3 class="{{ like_length|color_changer:like_length }}">{{ like_length }}</h3>
          {% if flag %}
          <button class="btn btn-danger" type="submit">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
              class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
              <path
                d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z" />
            </svg>
          </button>
          {% else %}
          <button class="btn btn-outline-danger" type="submit">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart"
              viewBox="0 0 16 16">
              <path
                d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z" />
            </svg>
          </button>
          {% endif %}
        </form>
      </div>
      <div class="d-flex">
        <a href="{% url 'articles:reviews' %}" class="btn btn-outline-dark">목록으로</a>
        {% if article.user == request.user %}
        <a href="{% url 'articles:update' article.pk %}" class="btn btn-primary ms-auto" style="width: 5rem;">수정</a>
        <a href="{% url 'articles:delete' article.pk %}" class="btn btn-danger ms-3" style="width: 5rem;">삭제</a>
        {% endif %}
      </div>
      {% if request.user.is_authenticated %}
      <div class="my-5">
        <form action="" method="POST" class="w-100">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_class="btn-outline-dark" button_type="submit" content="작성" style="width: 5rem;" %}
        </form>
      </div>
      {% else %}
      <div class="mt-3">
        <p>댓글 작성은 로그인 후에 가능합니다.</p>
      </div>
      {% endif %}
    </div>

    <table class="table table-borderless">
      <tbody>
        {% for comment in article.comment_set.all %}
        <tr>
          <th class="col-1 text-center">
            <a href="{% url 'accounts:detail' comment.user.pk %}">
              {{ comment.user }}
            </a>
          </th>
          <td class="col-10">
            <div>
              {% if request.resolver_match.url_name == "comment_update" and comment.pk == target_comment.pk %}
              <div>
                <form action="" method="POST" class="form">
                  {% csrf_token %}
                  {% bootstrap_form comment_form %}
                  {% bootstrap_button button_type="submit" content="수정완료" %}
                  <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary">취소</a>
                </form>
              </div>
              {% else %}
              {{ comment.content }}
              {% endif %}
            </div>
          </td>
          <td class="col-1 text-center">
            <a href="{% url 'articles:comment_update' article.pk comment.pk %}">수정</a>
            <a href="{% url 'articles:comment_delete' article.pk comment.pk %}">삭제</a>
          </td>
        </tr>
        {% empty %}
        <div class="text-center mt-5">
          <svg style="width: 5rem; height: 5rem;" xmlns="http://www.w3.org/2000/svg" width="16" height="16"
            fill="currentColor" class="bi bi-emoji-frown animate__animated animate__bounceIn" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
            <path
              d="M4.285 12.433a.5.5 0 0 0 .683-.183A3.498 3.498 0 0 1 8 10.5c1.295 0 2.426.703 3.032 1.75a.5.5 0 0 0 .866-.5A4.498 4.498 0 0 0 8 9.5a4.5 4.5 0 0 0-3.898 2.25.5.5 0 0 0 .183.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z" />
          </svg>
          <h1 class="mt-4 mb-2 display-6 animate__animated animate__bounceIn">
            아직 댓글이 없어요!
          </h1>
          <p class="lead fs-6 animate__animated animate__bounceIn">첫 댓글을 작성해보세요!</p>
        </div>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>


</div>
{% endblock body %}

articles/templates/articles/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

<div class="container w-50 mb-5">
  {% if request.resolver_match.url_name == "create" %}
  <h1 class="mt-5 mb-3">글쓰기</h1>
  <form action="" method="POST" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="작성완료" %}
    <a href="{% url 'articles:reviews' %}" class="btn btn-primary ms-2">돌아가기</a>
  </form>
  {% else %}
  {% if user == article.user or user.is_superuser %}
  <h1>수정하기</h1>
  <form action="" method="POST" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="수정완료" %}
    <a href="{% url 'articles:reviews' %}" class="btn btn-primary ms-2">돌아가기</a>
  </form>
  {% else %}
  <h1>권한이 없습니다.</h1>
  <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">돌아가기</a>
  {% endif %}
  {% endif %}
</div>

{% endblock body %}

articles/templates/articles/intro.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MCU</title>
  <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square-round.css" rel="stylesheet">
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
  <link rel="shortcut icon" href="{% static 'images/film.png' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>
    html {
      background-color: black;
    }

    body {
      animation: fadeIn;
      animation-duration: 5s;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg py-3 bg-black">
    <div class="container">
      <a class="navbar-brand text-light" href="{% url 'articles:index' %}"><b class="fs-1 p-3">MCU</b></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mx-0">
          <li class="nav-item">
            <a class="nav-link active mx-2 p-3 text-light align-bottom nav-hover" aria-current="page"
              href="{% url 'articles:intro' %}">MCU소개</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active mx-2 p-3 text-light nav-hover" href="{% url 'articles:create' %}">글쓰기</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active mx-2 p-3 nav-hover" aria-current="page" href="https://github.com/"
              target="_blank">
              <img src="{% static 'images/github.png' %}" alt="" style="width: 1.2rem; height: 1.2rem;">
            </a>
          </li>
        </ul>
        <ul class="navbar-nav d-flex">
          {% if request.user.is_authenticated %}
          <li class="nav-item mx-2">
            <a class="nav-link active p-3 text-light nav-hover" href="{% url 'accounts:detail' request.user.pk %}">
              {{ request.user.username }}
            </a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link active p-3 text-light nav-hover" aria-current="page"
              href="{% url 'accounts:logout' %}">로그아웃</a>
          </li>
          {% else %}
          <li class="nav-item mx-2">
            <a class="nav-link active p-3 text-light nav-hover" aria-current="page"
              href="{% url 'accounts:login' %}">로그인</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link active p-3 text-light nav-hover" aria-current="page"
              href="{% url 'accounts:signup' %}">회원가입</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="mcu-intro bg-black d-flex flex-column align-items-center">

    <div class="snap-item item-height item-start">
      <img src="https://dummyimage.com/600x400/000000/000000.png" class="h-25" alt="...">
    </div>

    <div class="snap-item item-height item-1">
      <img src="{% static 'images/image_6.png' %}" class="w-100 rounded-5" alt="...">
    </div>
    <div class="snap-item item-height item-2">
      <img src="{% static 'images/image_1.png' %}" class="w-100 rounded-5" alt="...">
    </div>

    <div class="snap-item item-height item-3">
      <img src="{% static 'images/image_2.png' %}" class="w-100 rounded-5" alt="...">
    </div>

    <div class="snap-item item-height item-4">
      <img src="{% static 'images/image_3.png' %}" class="w-100 rounded-5" alt="...">
    </div>

    <div class="snap-item item-height item-5">
      <img src="{% static 'images/image_4.png' %}" class="w-100 rounded-5" alt="...">
    </div>

    <div class="snap-item item-height item-6">
      <img src="{% static 'images/image_5.png' %}" class="w-100 rounded-5" alt="...">
    </div>
    <div class="snap-item item-height item-6">
      <img src="https://dummyimage.com/600x400/000000/000000.png" style="width: 10%;" alt="...">
    </div>

    <div class="snap-item item-height item-end text-center mb-5">
      <a href="{% url 'articles:index' %}" class="btn btn-outline-light btn-lg w-50">목록으로 돌아가기</a>
    </div>
  </div>

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous"></script>
</body>


</html>