accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("update/<int:pk>/", views.update, name="update"),
    path("<int:pk>/password/", views.change_pw, name="password"),
    path("<int:pk>/withdrawal/", views.withdrawal, name="withdrawal"),
]

articles/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = "articles"


urlpatterns = [
    path("reviews/", views.reviews, name="reviews"),
    path("search/", views.search, name="search"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
    path("<int:pk>/add-like", views.add_like, name="add-like"),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/update/",
        views.comment_update,
        name="comment_update",
    ),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

# 정적 파일 설정
# https://docs.djangoproject.com/en/4.1/howto/static-files/

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("index.urls")),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [
    path("", views.index, name="index"),
    path("intro/", views.intro, name="intro"),
    path("contrib/", views.contrib, name="contrib"),
]

templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MCU</title>
  <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square-neo.css" rel="stylesheet">
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
  {% bootstrap_css %}
  <link rel="shortcut icon" href="{% static 'images/film.png' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
</head>

<body>
  <nav class="navbar navbar-expand-lg py-3 position-sticky top-0 bg-black" style="z-index: 1;">
    <div class="p-0 m-0 animate__animated animate__fadeIn"
      style="width: 13%; height: 90%; z-index: 100; position: absolute;">
      {% if messages %}
      {% for message in messages %}
      <div class="toast show text-bg-{{ message.tags }} mb-3" aria-live="assertive" aria-atomic="true"
        style="position: relative; top: 2rem; left: 2rem;">
        <div class="toast-header">
          <strong class="me-auto">알림
          </strong>
          <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">
          {% if "이름" in message.message %}
          <p>{{ message }}</p>
          <div class="text-end">
            <a href="{% url 'accounts:detail' request.user.pk %}" class="btn btn-primary btn-sm">입력하러 가기</a>
          </div>
          {% else %}
          {{ message }}
          {% endif %}
        </div>
      </div>
      {% endfor %}
      {% endif %}
    </div>
    <div class="container">
      <a class="navbar-brand text-light" href="{% url 'index:intro' %}"><b class="fs-1 p-3">MCU</b></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav me-auto mx-0">
          <li class="nav-item">
            <a class="nav-link active p-2 text-light align-bottom nav-hover" aria-current="page"
              href="{% url 'articles:reviews' %}">게시판</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active p-2 text-light nav-hover" href="{% url 'articles:create' %}">글쓰기</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active p-2 text-light nav-hover" href="{% url 'index:contrib' %}">Contributors</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active p-2 nav-hover" aria-current="page" href="https://github.com/" target="_blank">
              <img src="{% static 'images/github.png' %}" alt="" style="width: 1.2rem; height: 1.2rem;">
            </a>
          </li>
        </ul>
        <form class="d-flex" role="search" method='POST' action="{% url 'articles:search' %}">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="검색" name='search'>
          <button class="btn btn-outline-light me-2" type="submit" style="width: 5rem;">검색</button>
        </form>
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active text-light nav-hover mx-0"
              href="{% url 'accounts:detail' request.user.pk %}">프로필</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active text-light nav-hover mx-0" aria-current="page"
              href="{% url 'accounts:logout' %}">로그아웃</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link active text-light nav-hover mx-0" aria-current="page"
              href="{% url 'accounts:login' %}">로그인</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active text-light nav-hover mx-0" aria-current="page"
              href="{% url 'accounts:signup' %}">회원가입</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% block body %}
  {% endblock body %}

  {% bootstrap_javascript %}
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous"></script>
</body>

</html>